resolver: nightly-2020-11-11
packages:
- .
extra-deps:
- polysemy-1.4.0.0
- polysemy-methodology-0.1.6.0
- Cabal-3.0.2.0
- co-log-polysemy-0.0.1.2
- polysemy-plugin-0.2.5.2
- polysemy-zoo-0.7.0.1
- polysemy-vinyl-0.1.2.0
- polysemy-extra-0.1.4.0
- compact-0.2.0.0
allow-newer: true
